Create `make release` task
Restructured release components to be more consistent. Also kept the sub release tasks separate in case we need to release any given component quickly/separately.

diff --git a/etc/build/tag_release b/etc/build/tag_release
--- a/etc/build/tag_release
+++ b/etc/build/tag_release
@@ -1,13 +1,23 @@
 #!/usr/bin/env bash
 
-if [ -z "$TRAVIS_BUILD_NUMBER" ]; then
-	echo "Only travis can tag a release"
-	exit 1
+
+version=`cat VERSION`
+commit=`cat COMMITID`
+
+if [ -z $version ]
+then
+        echo "No version found for this commit! Aborting release"
+        exit 1
 fi
 
-export PACH_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
-export VERSION=`make -s version 2>&1`
-echo "Tagging this build as: v$VERSION"
-git tag "v$VERSION"
+if [ -z $commit ]
+then
+        echo "No commit found for this release! Aborting release"
+        exit 1
+fi
+
+echo "--- Tagging release at ($commit)  w version: $version"
+echo "Tagging this build as: v$version"
+git tag "v$version" $commit
 echo "Pushing tags ..."
-git push --quiet https://${GITHUB_RELEASE_TOKEN}@github.com/pachyderm/pachyderm --tags > /dev/null 2>&1
+git push --quiet --tags > /dev/null 2>&1
