automate console release from core repo (#8441)
* console release job

* resuse release-github job

* fix prettier violation

* remove automated proto version bump

* address more code review comments

* few git corrections

* ensures PR is merged before triggering a console release

diff --git a/.circleci/main.yml b/.circleci/main.yml
--- a/.circleci/main.yml
+++ b/.circleci/main.yml
@@ -1081,7 +1081,67 @@ jobs:
                 echo "regular release."
                 gh release create --draft ${CIRCLE_TAG} --title ${CIRCLE_TAG:1} ./dist-pach/pachctl/pachctl_${CIRCLE_TAG:1}* ./dist-pach/mount-server/mount-server_${CIRCLE_TAG:1}* --generate-notes
             fi
+  console-release-draft:
+    docker:
+      - image: cimg/base:stable
+    steps:
+      - gh/setup:
+          version: 2.13.0
+      - run:
+          name: create github console release draft
+          command: |
+            if [[ $CIRCLE_TAG == *"-"* ]];
+              then
+                  echo "git tag has - assuming its a prerelease."
+                  parentBranch=master
+              else
+                  echo "regular release."
+                  parentBranch=${CIRCLE_TAG:1}
+              fi
+            git clone https://github.com/pachyderm/haberdashery.git haberdashery
+            cd haberdashery
+            git checkout -b release-${CIRCLE_TAG:1} ${parentBranch}
+            tmp=$(mktemp)
+            jq --arg val "${CIRCLE_TAG:1}-${CIRCLE_SHA1}" '.pachyderm = $val' version.json > "$tmp" && mv "$tmp" version.json
+            jq --arg val "${CIRCLE_SHA1}" '.pachReleaseCommit = $val' version.json > "$tmp" && mv "$tmp" version.json
+            jq --arg val "${CIRCLE_TAG:1}" '.pachctl = $val' version.json > "$tmp" && mv "$tmp" version.json
+            git add --all
+            git commit -m "bump pachyderm version"
+            git push origin release-${CIRCLE_TAG:1}
+            PR=$(gh pr create --base ${parentBranch} --title "bump pach version for release ${CIRCLE_TAG:1}" --body "bump pach version" --repo pachyderm/haberdashery)
+            gh pr merge ${PR} --auto --repo pachyderm/haberdashery
+            gh pr checks ${PR} --watch --interval 10 --repo pachyderm/haberdashery
+            STATE=$(gh pr view ${PR} --json state --jq .state --repo pachyderm/haberdashery)
+            if [[ "${STATE}" != "MERGED" ]]; then
+              echo "review console PR ${PR} for failures. It is not merged"
+              exit 1
+            fi
+            sleep 2 # in case we create release to fast
+            if [[ $CIRCLE_TAG == *"-"* ]];
+              then
+                  echo "git tag has - assuming prerelease."
+                  gh release create --draft ${CIRCLE_TAG:1}-1 --tittle ${CIRCLE_TAG:1}-1 --target $parentBranch --generate-notes --prerelease --repo pachyderm/haberdashery
+              else
+                  echo "regular release."
+                  gh release create --draft ${CIRCLE_TAG:1}-1 --tittle ${CIRCLE_TAG:1}-1 --target $parentBranch --generate-notes --repo pachyderm/haberdashery
+              fi
+            SECONDS=0
+            while :; do
+                docker pull pachyderm/haberdashery:${CIRCLE_TAG:1}-1 2>/dev/null && break
+                if (( $SECONDS > 1 )); then
+                    printf 'Waited 10 minutes for console docker image, inspect console relase at https://app.circleci.com/pipelines/gh/pachyderm/haberdashery for failures\n' >&2
+                    exit 1
+                fi
+                sleep 1
+            done
   release-github:
+    parameters:
+      repo:
+        type: string
+        default: pachyderm/pachyderm
+      tag:
+        type: string
+        default: ${CIRCLE_TAG}
     docker:
       - image: cimg/base:stable
     steps:
@@ -1093,7 +1153,7 @@ jobs:
       - run:
           name: create github release
           command: |
-            gh release edit ${CIRCLE_TAG} --draft=false
+            gh release edit << parameters.tag >> --draft=false --repo << parameters.repo >>
   release-docker-hub:
     docker:
       - image: cimg/base:stable
@@ -1336,6 +1396,13 @@ workflows:
             - build-pachctl-bin
             - publish-chart-preview
             - release-github-draft
+      - console-release-draft:
+          filters: *only-release-tags
+          requires:
+            - build-docker-images
+            - build-pachctl-bin
+            - publish-chart-preview
+            - release-github-draft
       - sign-off:
           filters: *only-release-tags
           type: approval
@@ -1353,13 +1420,21 @@ workflows:
       #    requires:
       #      - sign-off
       - release-github:
+          name: github-release-pach-core
+          filters: *only-release-tags
+          requires:
+            - sign-off
+      - release-github:
+          name: github-release-console
+          repo: pachyderm/haberdashery
+          tag: ${CIRCLE_TAG:1}-1
           filters: *only-release-tags
           requires:
             - sign-off
       - release-hombrew-tap:
           filters: *only-release-tags
           requires:
-            - release-github #current homebrew tap repo uses gh release, but later can be changed to pipeline artifacts to remove deps
+            - github-release-pach-core #current homebrew tap repo uses gh release, but later can be changed to pipeline artifacts to remove deps
       - helm-publish:
           name: publish-helm-chart
           filters: *only-release-tags
