more cleanup, fixes mismatch in dev and prod image name

diff --git a/scripts/dev-launch b/scripts/dev-launch
--- a/scripts/dev-launch
+++ b/scripts/dev-launch
@@ -1,8 +1,13 @@
 #!/bin/sh
 # Launch pfs in single node mode, using the current source tree to build the image.
 ###############################################################################
-set -E          # pass trap handlers down to subshells
-#set -x         # execution tracing debug messages
+
+set -Ee          # pass trap handlers down to subshells, exit on error
+
+DIR="$(cd "$(dirname "${0}")" && pwd)"
+cd "${DIR}"
+
+source "${DIR}/lib/lib.sh"
 
 HELP="A script to build pfs from the source directory and launch\npfs in single node mode.\nUsage: $0 [-p port] [-i image]"
 
@@ -10,21 +15,20 @@ HELP="A script to build pfs from the source directory and launch\npfs in single 
 OPTIND=1         # Reset in case getopts has been used previously in the shell.
 
 # Initialize our own variables:
-PORT="650"
-IMAGE="pfs"
+PORT="${PFS_PORT}"
+IMAGE="${PFS_IMAGE}"
 
 while getopts "p:i:" opt; do
     case "$opt" in
     \?)  echo $HELP
         exit 0
         ;;
-    p)  PORT=$OPTARG
+    p)  PORT="${OPTARG}"
         ;;
-    i)  IMAGE=$OPTARG
+    i)  IMAGE="${OPTARG}"
         ;;
     esac
 done
-echo -n "Building container $IMAGE ... (this requires sudo)"
-sudo docker build -t $IMAGE .
-echo "done.\n. Launching single node server."
-scripts/launch -i $IMAGE /go/bin/shard 0-1 localhost
+
+log_command sudo docker build -t "${IMAGE}" "$(cd "${DIR}/.." && pwd)"
+log_command "${DIR}/launch" -i "${IMAGE}"
