more cleanup

diff --git a/scripts/dev-post-receive b/scripts/dev-post-receive
--- a/scripts/dev-post-receive
+++ b/scripts/dev-post-receive
@@ -4,7 +4,15 @@
 # push that image to the local registry
 # restart the services in the cluster
 ###############################################################################
-REPOSITORY_BASENAME=$(basename "$PWD")
+
+set -Ee          # pass trap handlers down to subshells, exit on error
+
+DIR="$(cd "$(dirname "${0}")" && pwd)"
+cd "${DIR}"
+
+source "${DIR}/lib/lib.sh"
+
+REPOSITORY_BASENAME="$(cd "$(dirname "${0}")/.." && pwd)"
 REPOSITORY_BASENAME=${REPOSITORY_BASENAME%.git}
 TMPDIR="/tmp/${REPOSITORY_BASE_NAME}"
 if [ ! -d "${TMPDIR}" ]; then
@@ -19,7 +27,7 @@ fleetctl start "${GIT_WORK_TREE}/deploy/static/dev/gitdaemon.service"
 fleetctl start "${GIT_WORK_TREE}/deploy/static/dev/registry.service"
 fleetctl start "${GIT_WORK_TREE}/deploy/static/dev/announce-registry.service"
 # Build the image
-REG=$(etcdctl get /pfs/registry)
+REG="$(etcdctl get /pfs/registry)"
 sudo docker build -t "${REG}/${REPOSITORY_BASENAME}" "${GIT_WORK_TREE}"
 sudo docker push "${REG}/${REPOSITORY_BASENAME}"
 # Restart the pfs services
