Few fixes to launch script.

diff --git a/scripts/launch b/scripts/launch
--- a/scripts/launch
+++ b/scripts/launch
@@ -11,6 +11,15 @@ if [ $# -gt 1 ] ; then
     echo $USAGE
     exit 1;
 fi
+
+BTRFS_VERSION="$(which btrfs)" || { echo 'Please install btrfs-tools. (apt-get install btrfs-tools)' ; exit 1; }
+DOCKER_VERSION="$(docker --version | awk '{ print $3 }')"
+
+if [ "$DOCKER_VERSION" != "1.5.0," ] ; then
+    echo "docker 1.5.0 required"
+    echo "See: https://docs.docker.com/installation/ubuntulinux/#docker-maintained-package-installation"
+    exit 1;
+fi
 CMD="$0"
 CMD_DIR="$(cd "$(dirname "$CMD")" && pwd)"
 PFS_DIR=~/.pfs
@@ -30,7 +39,8 @@ echo "done."
 sudo docker kill pfs 2>/dev/null >/dev/null
 sudo docker rm pfs 2>/dev/null >/dev/null
 echo "Launching server... (this requires sudo)"
-sudo docker run \
+echo "Container id:"
+sudo docker run -d \
     --privileged=true \
     --name pfs \
     -v /:/host:ro \
@@ -40,5 +50,11 @@ sudo docker run \
     -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" \
     -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" \
     -p "$PORT":80 \
-    -ti pachyderm/pfs \
+    -i pachyderm/pfs \
     /go/bin/master 0-1
+echo "done."
+echo "Server is listening on localhost:$PORT"
+echo "Logging to ~/.pfs/log/log-0-1"
+echo "Data is stored in ~/.pfs/vol"
+echo "To kill:"
+echo "docker kill pfs"
