more cleanup, scripts/build

diff --git a/scripts/pfs-install b/scripts/pfs-install
--- a/scripts/pfs-install
+++ b/scripts/pfs-install
@@ -2,19 +2,21 @@
 # Install a git repo on a pfs cluster.
 # Run this from the route of your pfs repo.
 ###############################################################################
-set -E          # pass trap handlers down to subshells
-#set -x         # execution tracing debug messages
 
-USAGE="Usage: $0 host"
+set -Ee          # pass trap handlers down to subshells, exit on error
 
-# --- Options processing -------------------------------------------
+DIR="$(cd "$(dirname "${0}")" && pwd)"
+cd "${DIR}"
+
+source "${DIR}/lib/lib.sh"
+
+USAGE="Usage: ${0} host"
+
 if [ $# != 1 ] ; then
-    echo $USAGE
-    exit 1;
+    echo "${USAGE}" >&2
+    exit 1
 fi
-CMD="$0"
-CMD_DIR="$(cd "$(dirname "$CMD")" && pwd)"
-HOST="$1"
+HOST="${1}"
 
 REPO=$(basename `pwd`)
 REMOTE="$HOST":/home/core/"$REPO".git
@@ -24,7 +26,7 @@ echo "Installing $REMOTE"
 rm -rf /tmp/"$REPO".git
 git clone --bare . /tmp/"$REPO".git
 scp -rqC /tmp/"$REPO".git core@"$REMOTE"
-scp -rqC "$CMD_DIR"/post-receive core@"$REMOTE"/hooks/post-receive
+scp -rqC "${DIR}/post-receive" "core@${REMOTE}/hooks/post-receive"
 git remote remove pachyderm
 git remote add pachyderm git://"$HOST"/home/core/"$REPO".git
 
